name: Thử nghiệm đọc file README    #Tên quy trình

on:
  push:
    branches: ("main)     #Khởi chạy có code mới đẩy lên nhánh main

jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - xin chào
        run: echo "Hello HUTECH"

      - name: Bước 2 - Tải code
        uses: actions/checkout@v6.0.2

      - name: Bước 3 - Đọc file
        run: cat README.md
